version: '3.8'
services:
  app:
    build: .
    ports: ["5000:5000"]
    depends_on: [mongo, redis]
  mongo:
    image: mongo
    ports: ["27017:27017"]
  redis:
    image: redis:alpine
    ports: ["6379:6379"]
